//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "RecipeCollection")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub collection_name: String,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recipe_collection_recipe::Entity")]
    RecipeCollectionRecipe,
}

impl Related<super::recipe_collection_recipe::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeCollectionRecipe.def()
    }
}

impl Related<super::recipe::Entity> for Entity {
    fn to() -> RelationDef {
        super::recipe_collection_recipe::Relation::Recipe.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::recipe_collection_recipe::Relation::RecipeCollection
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
