//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "CousineName")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recipe_cousine::Entity")]
    RecipeCousine,
}

impl Related<super::recipe_cousine::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeCousine.def()
    }
}

impl Related<super::recipe::Entity> for Entity {
    fn to() -> RelationDef {
        super::recipe_cousine::Relation::Recipe.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::recipe_cousine::Relation::CousineName.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
