//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub mod prelude;

pub mod comment;
pub mod cuisine_name;
pub mod diet_name;
pub mod ingredient_name;
pub mod login_token;
pub mod meal_name;
pub mod recipe;
pub mod recipe_collection;
pub mod recipe_collection_recipe;
pub mod recipe_cuisine;
pub mod recipe_diet;
pub mod recipe_ingredient;
pub mod recipe_meal;
pub mod recipe_source;
pub mod source;
pub mod user;
