//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::ingredientname::Entity as Ingredientname;
pub use super::recipe::Entity as Recipe;
pub use super::recipecousine::Entity as Recipecousine;
pub use super::recipeingredient::Entity as Recipeingredient;
pub use super::recipetype::Entity as Recipetype;
