//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::comment::Entity as Comment;
pub use super::cuisine_name::Entity as CuisineName;
pub use super::diet_name::Entity as DietName;
pub use super::ingredient_name::Entity as IngredientName;
pub use super::meal_name::Entity as MealName;
pub use super::recipe::Entity as Recipe;
pub use super::recipe_collection::Entity as RecipeCollection;
pub use super::recipe_collection_recipe::Entity as RecipeCollectionRecipe;
pub use super::recipe_cuisine::Entity as RecipeCuisine;
pub use super::recipe_diet::Entity as RecipeDiet;
pub use super::recipe_ingredient::Entity as RecipeIngredient;
pub use super::recipe_meal::Entity as RecipeMeal;
pub use super::user::Entity as User;
