//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "RecipeCollectionRecipe")]
pub struct Model {
    pub public: Option<bool>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub recipe_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub collection_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::recipe::Entity",
        from = "Column::RecipeId",
        to = "super::recipe::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Recipe,
    #[sea_orm(
        belongs_to = "super::recipe_collection::Entity",
        from = "Column::CollectionId",
        to = "super::recipe_collection::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RecipeCollection,
}

impl Related<super::recipe::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipe.def()
    }
}

impl Related<super::recipe_collection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeCollection.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
