//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "RecipeCuisine")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recipe_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub cuisine_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cuisine_name::Entity",
        from = "Column::CuisineId",
        to = "super::cuisine_name::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CuisineName,
    #[sea_orm(
        belongs_to = "super::recipe::Entity",
        from = "Column::RecipeId",
        to = "super::recipe::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Recipe,
}

impl Related<super::cuisine_name::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CuisineName.def()
    }
}

impl Related<super::recipe::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipe.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
